### ISSUE TITLE
Bug: The url is wrong when clicking on a block or account on the block page

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#8]
When using empty RPC in the url pattern, like tix.nanos.cc/#/

Link become: https://tix.nanos.cc/#/undefined/block/CC5D945BD3C39865340B93E721706B899EB985DA213B6B366811A387C97D9881

Which works but has "undefined" in it.

**Comment by thelamer** [comment]
This is resolved in https://github.com/linuxserver/nano-wallet/releases/tag/1.0.6

**Comment by Joohansson** [comment]
Was that really committed? I can't find the fix for it and I still see the same.

**Comment by thelamer** [comment]
Pretty sure https://github.com/linuxserver/nano-wallet/commit/7a3230789404b027c0fdd18aef7d6b1c3b1e6817

**Comment by Joohansson** [comment]
I have that commit applied yet seeing the wrong URL with "undefined" RPC reference.

**Comment by thelamer** [comment]
Yeah just a break in testing here, you can manually enter the link but the links we generate are bad, will patch this in.

**Comment by thelamer** [comment]
This is fixed in https://github.com/linuxserver/nano-wallet/commit/4c3438134cd103040fdcda0ea2a378d517bace5e
